-- CREATE DATABASE | SCHEMA JAVA10_SHOPPING_MANUAL
-- RUN a SQL statement: Ctrl Enter
CREATE SCHEMA JAVA10_SHOPPING_MANUAL DEFAULT CHAR SET utf8mb4;

USE JAVA10_SHOPPING_MANUAL;

-- CREATE TABLE LoaiHang, MatHang
-- DROP TABLE LoaiHang, MatHang
DROP TABLE MatHang;
DROP TABLE LoaiHang;

CREATE TABLE MatHang(
	MaMH INT,
    TenMaH VARCHAR(255) NOT NULL,
    GiaBan DOUBLE NOT NULL,
    GiaMua DOUBLE NOT NULL,
    ChatLieu VARCHAR(255) NOT NULL,
    MauSac VARCHAR(255) NOT NULL,
    HinhAnh VARCHAR(255) NOT NULL,
    SoLuong INT NOT NULL,
    MaLoai INT,
    CONSTRAINT PK_MatHang PRIMARY KEY (MaMH)
    -- CONSTRAINT FK_MatHang_LoaiHang FOREIGN KEY (MaLoai) REFERENCES LoaiHang(MaLoai)
);

CREATE TABLE LoaiHang(
	MaLoai INT PRIMARY KEY,
    TenLoai VARCHAR(255) NOT NULL
);

ALTER TABLE MatHang ADD 
CONSTRAINT FK_MatHang_LoaiHang FOREIGN KEY (MaLoai) REFERENCES LoaiHang(MaLoai);

-- ADD COLUMN NgayTao
ALTER TABLE LoaiHang ADD
NgayTao DATETIME NOT NULL;

-- REMOVE COLUMN NgayTao
ALTER TABLE LoaiHang DROP COLUMN NgayTao;

-- TRUNCATE TABLE 
SELECT * FROM MatHang;

DELETE FROM MatHang;

TRUNCATE TABLE MatHang; -- Test data

